### ISSUE TITLE
Skin manager error.

### ISSUE THREAD

**Issue by hoehoetvhss** [Camotoy/GeyserSkinManager#15]
`
[12:22:24 ERROR]: Could not pass event PlayerJoinEvent to GeyserSkinManager v1.5-SNAPSHOT
java.lang.NoSuchMethodError: 'org.geysermc.connector.network.session.auth.BedrockClientData org.geysermc.connector.network.session.GeyserSession.getClientData()'
        at com.github.camotoy.geyserskinmanager.common.skinretriever.GeyserSkinRetriever.getBedrockSkin(GeyserSkinRetriever.java:55) ~[GeyserSkinManager.jar:?]
        at com.github.camotoy.geyserskinmanager.spigot.listener.PaperEventListener.onPlayerJoin(PaperEventListener.java:23) ~[GeyserSkinManager.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor323.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-15]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[paper-1.18.jar:git-Paper-15]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[paper-1.18.jar:git-Paper-15]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:306) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1635) ~[paper-1.18.jar:git-Paper-15]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-15]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1469) ~[paper-1.18.jar:git-Paper-15]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1263) ~[paper-1.18.jar:git-Paper-15]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-15]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        `

`
[22:15:50] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to GeyserSkinManager v1.5-SNAPSHOT
java.lang.NoSuchMethodError: 'org.geysermc.connector.network.session.auth.BedrockClientData org.geysermc.connector.network.session.GeyserSession.getClientData()'
	at com.github.camotoy.geyserskinmanager.common.skinretriever.GeyserSkinRetriever.getBedrockSkin(GeyserSkinRetriever.java:55) ~[GeyserSkinManager.jar:?]
	at com.github.camotoy.geyserskinmanager.spigot.listener.PaperEventListener.onPlayerJoin(PaperEventListener.java:23) ~[GeyserSkinManager.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor321.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-25]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[paper-1.18.jar:git-Paper-25]
	at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[paper-1.18.jar:git-Paper-25]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:306) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.18.jar:git-Paper-25]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.jar:git-Paper-25]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.jar:git-Paper-25]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-25]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-25]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`
	
	

Dump: https://dump.geysermc.org/3CRDaB2g7R54oS8bBxL3XIssNc2k7da1

**Comment by hoehoetvhss** [comment]
This part seems to have been resolved.
