### ISSUE TITLE
The Bedrock version of the skin does not reflect properly.

### ISSUE THREAD

**Issue by Fuwayuka** [Camotoy/GeyserSkinManager#17]
The skin of the Bedrock version looks broken when viewed from the Java version.

I'm using the latest version of both plugins.

Here is the error log

[23:00:46] [Netty Worker IO Thread #9/INFO]: [BEZeus11271|/192.168.50.161:0] <-> ServerConnector [akarin] has connected
[23:00:46] [WebSocketConnectReadThread-53/INFO] [Geyser-BungeeCord]: Got a message from skin uploader: received a skin with invalid geometry: the image width and height doesn't match the geometry data width and height
[23:00:47] [Netty Worker IO Thread #9/INFO]: [SAcc] BEZeus11271 Login from --
[23:00:47] [pool-17-thread-1/WARN] [GeyserSkinManager-BungeeCord]: Failed to upload player skin for 00000000-0000-0000-0009-01f3115b17f3
[23:00:47] [pool-17-thread-1/ERROR]: java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:00:47] [pool-17-thread-1/ERROR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.desktop/sun.awt.image.IntegerInterleavedRaster.setDataElements(IntegerInterleavedRaster.java:297)
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.desktop/java.awt.image.BufferedImage.setRGB(BufferedImage.java:1017)
[23:00:47] [pool-17-thread-1/ERROR]: 	at com.github.camotoy.geyserskinmanager.common.SkinUtils.toBufferedImage(SkinUtils.java:184)
[23:00:47] [pool-17-thread-1/ERROR]: 	at com.github.camotoy.geyserskinmanager.common.SkinUploader.uploadSkinInner(SkinUploader.java:57)
[23:00:47] [pool-17-thread-1/ERROR]: 	at com.github.camotoy.geyserskinmanager.common.SkinUploader.lambda$uploadSkin$0(SkinUploader.java:45)
[23:00:47] [pool-17-thread-1/ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:00:47] [pool-17-thread-1/ERROR]: 	... 3 more

**Comment by Fuwayuka** [comment]
I've solved the problem, so I'll close it.

What I tried
Remove the BedrockSkinUtility Mod from the client.
Delete the GeyserSkinManager folder and jar file and reinsert them.
Remove the GeyserSkinManager folder and jar file, and re-install it. - Set force-show-skins to true in the config file.
Start again.
Now it's working properly.
