### ISSUE TITLE
The error occurs in environments using the latest Waterfall,Geyser and Floodgate.

### ISSUE THREAD

**Issue by Jumala9163** [Camotoy/GeyserSkinManager#21]
Hello

I get the following error when using the latest versions of Waterfall (Build#493), Geyser (Build#1112) and Floodgate (Build#68): The BE player skin is not visible to the Java player.

Please forgive me that my English is not very good.
Thank you.

```
Error dispatching event ServerConnectedEvent(player=JumalaSubBE, server=net.md_5.bungee.ServerConnection@98d52f99) to listener com.github.camotoy.geyserskinmanager.bungeecord.BungeecordSkinEventListener@30568ac9
java.lang.NoSuchMethodError: org/geysermc/connector/network/session/GeyserSession.getClientData()Lorg/geysermc/connector/network/session/auth/BedrockClientData; (loaded from file:/home/container/plugins/Geyser-BungeeCord.jar by PluginClassloader(desc=PluginDescription(name=Geyser-BungeeCord, main=org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin, version=2.0.4-SNAPSHOT, author=GeyserMC, depends=[], softDepends=[], file=plugins/Geyser-BungeeCord.jar, description=null, libraries=[]))) called from class com.github.camotoy.geyserskinmanager.common.skinretriever.GeyserSkinRetriever (loaded from file:/home/container/plugins/GeyserSkinManager-BungeeCord.jar by PluginClassloader(desc=PluginDescription(name=GeyserSkinManager-BungeeCord, main=com.github.camotoy.geyserskinmanager.bungeecord.GeyserSkinManager, version=1.5-SNAPSHOT, author=Camotoy, depends=[Geyser-BungeeCord], softDepends=[], file=plugins/GeyserSkinManager-BungeeCord.jar, description=null, libraries=[]))).
        at com.github.camotoy.geyserskinmanager.common.skinretriever.GeyserSkinRetriever.getBedrockSkin(GeyserSkinRetriever.java:55) ~[?:?]
        at com.github.camotoy.geyserskinmanager.bungeecord.BungeecordSkinEventListener.onServerConnected(BungeecordSkinEventListener.java:41) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:219) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:228) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:f33b035:493]
        at java.lang.Thread.run(Thread.java:889) ~[?:?]
```

**Comment by Camotoy** [comment]
Looks like you're using an older build. Download the one from the releases tab here instead.
