### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by davidgb8246** [Camotoy/GeyserSkinManager#23]
I wonder if you could make the plugin work on Bungeecord/Spigot 1.20

**Comment by nakanotti** [comment]
I my case ... WARN only.
- waterfall-1.20-536

```
[11:10:11 INFO]: Using mbed TLS based native cipher.
[11:10:11 INFO]: Using zlib based native compressor.
[11:10:11 INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536
[11:10:11 INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[11:10:11 INFO]: Epoll is working, utilising it!
[11:10:11 INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[11:10:11 INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[11:10:11 INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[11:10:11 INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[11:10:11 INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[11:10:11 INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[11:10:11 INFO] [Geyser-BungeeCord]: 拡張機能を読み込み中...
[11:10:11 INFO] [Geyser-BungeeCord]: 0 拡張機能を読み込みました
[11:10:11 INFO]: Loaded plugin Geyser-BungeeCord version 2.1.1-SNAPSHOT by GeyserMC
[11:10:11 INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:11 INFO]: Loaded plugin cmd_find version git:cmd_find:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:11 INFO]: Loaded plugin ViaVersion version 4.7.0 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[11:10:11 INFO]: Loaded plugin cmd_server version git:cmd_server:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:11 INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:11 INFO] [floodgate]: Took 124ms to boot Floodgate
[11:10:11 INFO]: Loaded plugin floodgate version 2.2.2-SNAPSHOT (b10-d572ec9) by GeyserMC
[11:10:11 INFO]: Loaded plugin cmd_send version git:cmd_send:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:11 INFO]: Loaded plugin GeyserSkinManager-BungeeCord version 1.6 by Camotoy
[11:10:11 INFO]: Loaded plugin ViaBackwards version 4.7.0 by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[11:10:11 INFO]: Loaded plugin bungee-rcon version 1.0.0 by Orblazer
[11:10:11 INFO]: Loaded plugin cmd_list version git:cmd_list:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:11 INFO]: Enabled plugin Geyser-BungeeCord version 2.1.1-SNAPSHOT by GeyserMC
[11:10:11 INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:11 INFO] [Geyser-BungeeCord]: ******************************************
[11:10:11 INFO] [Geyser-BungeeCord]: 
[11:10:11 INFO]: Enabled plugin cmd_find version git:cmd_find:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:11 INFO] [Geyser-BungeeCord]: Geyser バージョン 2.1.1-SNAPSHOT (git-master-f3cc93c) を読み込んでいます
[11:10:11 INFO] [Geyser-BungeeCord]: 
[11:10:11 INFO] [Geyser-BungeeCord]: ******************************************
[11:10:11 INFO] [ViaVersion]: Loading block connection mappings ...
[11:10:11 INFO] [ViaBackwards]: Loading translations...
[11:10:11 INFO] [ViaBackwards]: Registering protocols...
[11:10:11 INFO] [ViaVersion]: Using FastUtil Long2ObjectOpenHashMap for block connections
[11:10:11 INFO] [ViaVersion]: ViaVersion detected lowest supported version by the proxy: 1.8.x (47)
[11:10:11 INFO] [ViaVersion]: Highest supported version by the proxy: 1.20 (763)
[11:10:11 INFO] [ViaVersion]: Finished mapping loading, shutting down loader executor!
[11:10:12 INFO]: Enabled plugin ViaVersion version 4.7.0 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
[11:10:12 INFO]: Enabled plugin cmd_server version git:cmd_server:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:12 INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:12 INFO]: Enabled plugin floodgate version 2.2.2-SNAPSHOT (b10-d572ec9) by GeyserMC
[11:10:12 INFO]: Enabled plugin cmd_send version git:cmd_send:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:12 WARN]: Exception encountered when loading plugin: GeyserSkinManager-BungeeCord
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
	at com.github.camotoy.geyserskinmanager.relocations.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:178) ~[?:?]
	at com.github.camotoy.geyserskinmanager.relocations.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:466) ~[?:?]
	at com.github.camotoy.geyserskinmanager.relocations.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:354) ~[?:?]
	at com.github.camotoy.geyserskinmanager.relocations.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[?:?]
	at com.github.camotoy.geyserskinmanager.relocations.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413) ~[?:?]
	at com.github.camotoy.geyserskinmanager.common.Configuration.create(Configuration.java:46) ~[?:?]
	at com.github.camotoy.geyserskinmanager.bungeecord.GeyserSkinManager.onEnable(GeyserSkinManager.java:12) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
[11:10:12 INFO]: Enabled plugin ViaBackwards version 4.7.0 by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[11:10:12 INFO]: Binding rcon to address: 0.0.0.0/0.0.0.0:25575...
[11:10:12 INFO]: Enabled plugin bungee-rcon version 1.0.0 by Orblazer
[11:10:12 INFO]: Enabled plugin cmd_list version git:cmd_list:1.20-R0.1-SNAPSHOT:ec41547:536 by WaterfallMC
[11:10:12 WARN]: Using PROXY protocol for listener /0.0.0.0:25577, please ensure this listener is adequately firewalled.
[11:10:12 WARN]: Since PROXY protocol is in use, internal connection throttle has been disabled.
[11:10:12 INFO]: Listening on /0.0.0.0:25577
[11:10:12 INFO] [Geyser-BungeeCord]: Geyser を 0.0.0.0 で開始しました: 19132
[11:10:12 INFO] [Geyser-BungeeCord]: 完了 (1.344s)！ /geyser help を実行してください！
```

**Comment by nakanotti** [comment]
for more informations

- Paper 1.20 Build.2
- GeyserSkinManager-Spigot v1.6
```
[03:59:32 ERROR]: Error occurred while enabling GeyserSkinManager v1.6 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
	at com.github.camotoy.geyserskinmanager.relocations.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:178) ~[GeyserSkinManager-Spigot.jar:?]
	at com.github.camotoy.geyserskinmanager.relocations.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:466) ~[GeyserSkinManager-Spigot.jar:?]
	at com.github.camotoy.geyserskinmanager.relocations.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:354) ~[GeyserSkinManager-Spigot.jar:?]
	at com.github.camotoy.geyserskinmanager.relocations.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15) ~[GeyserSkinManager-Spigot.jar:?]
	at com.github.camotoy.geyserskinmanager.relocations.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3413) ~[GeyserSkinManager-Spigot.jar:?]
	at com.github.camotoy.geyserskinmanager.common.Configuration.create(Configuration.java:46) ~[GeyserSkinManager-Spigot.jar:?]
	at com.github.camotoy.geyserskinmanager.spigot.GeyserSkinManager.onEnable(GeyserSkinManager.java:19) ~[GeyserSkinManager-Spigot.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.jar:git-Paper-2]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.jar:git-Paper-2]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.20.jar:git-Paper-2]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.20.jar:git-Paper-2]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.20.jar:git-Paper-2]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.jar:git-Paper-2]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.jar:git-Paper-2]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.20.jar:git-Paper-2]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.20.jar:git-Paper-2]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[03:59:32 INFO]: [GeyserSkinManager] Disabling GeyserSkinManager v1.6
```

**Comment by Jens-Co** [comment]
There were some changes to Jackson on Geysers end. We need to relocate Jackson, I'll see if I can make a pr soon.

**Comment by Belialneutral** [comment]
Esta disponible para la versión 1.20 de java y bedrock de PeperMC

**Comment by Belialneutral** [comment]
Is the update available for the java version 1.20 of peperMC?

**Comment by mangosbangos** [comment]
Has the changes been made yet because I am unable to use the plug in on my server. It keeps coming up with the error code of "The plugin 'GeyserSkinManager' could not be enabled." The Plug in was working just fine on my 1.19.4 server and only crashed now that I've updated it to 1.20

**Comment by nakanotti** [comment]
I tried pull request #24.
It looks like it's working fine for Bungeecord/Spigot for 1.20.

**Comment by sorandno** [comment]
Didn't work with paper 1.20.1.

Will there be an update?

Waiting for update.

**Comment by Konicai** [comment]
There is an experimental build available on the discord.

**Comment by sorandno** [comment]
thank you
